### ISSUE TITLE
Multiple set without any get calls, results in ttl mismatch

### ISSUE THREAD

**Issue by sveisvei** [avoidwork/tiny-lru#37]
### Scenario 

```:javascript
const cache =  lru();
cache.set("foo", "bar");
// wait until TTL has passed
cache.set("foo", "baz");
const result = cache.get("foo");
console.log(typeof result === "undefined");
```
I do not expect the result to be "undefined", but rather expect it to be the "baz" value.
The second `set()` should IMO update the expiry property.

### Failing test:
```:javascript
exports.multiSetWithTTL = {
	setUp: function (done) {
		this.cache = lru(4, 10);
		done();
	},
	test: function (test) {
		this.cache.set("foo", "bar");
		setTimeout(function(){
			this.cache.set("foo", "baz");
			test.equal(this.cache.get("foo"), "baz", "should return baz");
			test.done();
		}.bind(this), 11);
	}
};
```

Want a PR for this? This fix would require a breaking change?
If this behaviour is expected, it should be documented in the README.

**Comment by avoidwork** [comment]
hi, this is an old bug. it came in with https://github.com/avoidwork/tiny-lru/commit/3fc4311fd492ab9e36c31519ebe2c89cde4c73e7#diff-63a47269ebaf7ac69e5cb1308e2091bcR145 and happens because the `expiry` isn't updated when the key exists. i'll fix it.

**Comment by sveisvei** [comment]
Thanx for fixing, adding test and releasing right away :).

**Comment by avoidwork** [comment]
hi, i need to revert this; i forgot why it was done this way. the hard expiration was put in place to stop cache items for staying valid forever which is possible in some places i use this.

**Comment by sveisvei** [comment]
Maybe a test communicates this scenario better, can help with a solution if you need.

**Comment by sveisvei** [comment]
@avoidwork Hello again. Any plans/thoughts here?

**Comment by avoidwork** [comment]
@sveisvei the change was reverted with a new version, so unless you specifically target 7.0.3 it's not going to behave differently.

**Comment by sveisvei** [comment]
Ok, fair enough. I would suggest you document this as a feature - because it breaks IMO expectations. 

I would be happy to help you out with a patch to support both cases, but I do not understand how a item can get stuck forever.

**Comment by avoidwork** [comment]
This shouldn't break expectation, because it's documented in the README at https://github.com/avoidwork/tiny-lru#ttl

From an ops pov, a set() is a get() under a specific context which mutates the record relationships. 2 years ago I ran into the problem of keys not expiring as planned because the get()s kept them in cache with valid expiry values.

**Comment by avoidwork** [comment]
This shouldn't break expectation, because it's documented in the README at https://github.com/avoidwork/tiny-lru#ttl

From an ops pov, a get() is a set() under a specific context which mutates the record relationships. 2 years ago I ran into the problem of keys not expiring as planned because the get()s kept them in cache with valid expiry values.

**Comment by avoidwork** [comment]
that said, there's no reason a new argument can't be introduced to set() for this use case.

**Comment by avoidwork** [comment]
i can likely land this corrected implementation over the weekend or on monday.

**Comment by sveisvei** [comment]
Thanx again.
